version: '3.8'

services:
  jenkins_agent1:
    image: jenkins/ssh-agent:jdk11
    privileged: true
    user: root
    container_name: $JENKINS_CONTAINER_NAME1
    expose:
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=$JENKINS_AGENT_SSH_PUBKEY
    secrets:
      - host_ssh_key
    networks:
      mynetwork:
        ipv4_address: 10.0.2.100

  jenkins_agent2:
    image: jenkins/ssh-agent:jdk11
    privileged: true
    user: root
    container_name: $JENKINS_CONTAINER_NAME2
    expose:
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=$JENKINS_AGENT_SSH_PUBKEY
    secrets:
      - host_ssh_key
    networks:
      mynetwork:
        ipv4_address: 10.0.2.101

secrets:
  host_ssh_key:
    file: ~/.ssh/id_rsa.pub

networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.2.100/28

